Specify geo_names arg in get_names()
Error:
Quitting from lines 63-70 (mapping_summary.Rmd)
   Error: processing vignette 'mapping_summary.Rmd' failed with diagnostics:
   Missing geo_names - please specify appropriate geography names.